export const data = [
  {
    id: "1M",
    name: "Champion Men's Script Logo T-Shirt",
    category: "men",
    image: "1.jpeg",
    price: 120,
    quantity: 1,
  },
  {
    id: "2M",
    name: "Tommy Hilfiger Men's Tino Logo T-Shirt",
    category: "men",
    image: "2.jpeg",
    price: 140,
    quantity: 1,
  },
  {
    id: "3M",
    name: "Under Armour Men's Tech™ Short Sleeve",
    category: "men",
    image: "3.jpeg",
    price: 100,
    quantity: 1,
  },
  {
    id: "1W",
    name: "DKNY Printed Flare Dress",
    category: "women",
    image: "4.jpeg",
    price: 150,
    quantity: 1,
  },
  {
    id: "2W",
    name: "Ruffled Georgette Shift Dress",
    category: "women",
    image: "5.jpeg",
    price: 170,
    quantity: 1,
  },
  {
    id: "3W",
    name: "Smocked-Waist Midi Dress",
    category: "women",
    image: "6.jpeg",
    price: 90,
    quantity: 1,
  },
  {
    id: "1K",
    name: "Big Boys Tuxedo Shirt and Bow",
    category: "kids",
    image: "8.jpeg",
    price: 190,
    quantity: 1,
  },
  {
    id: "2K",
    name: "Big Girl Wire Hem Dress",
    category: "kids",
    image: "9.jpeg",
    price: 70,
    quantity: 1,
  },
  {
    id: "3K",
    name: "Solid Twill Vest, Pants & Bowtie Set",
    category: "kids",
    image: "10.jpeg",
    price: 150,
    quantity: 1,
  },
  {
    id: "1S",
    name: "Memory Foam Rivver Sandals",
    category: "shoes",
    image: "11.jpeg",
    price: 45,
    quantity: 1,
  },
  {
    id: "2S",
    name: "Men's Adam Cap Toe Oxford",
    category: "shoes",
    image: "12.jpeg",
    price: 125,
    quantity: 1,
  },
  {
    id: "3S",
    name: "Men's Court Casper Casual Sneakers",
    category: "shoes",
    image: "13.jpeg",
    price: 65,
    quantity: 1,
  },
  {
    id: "4S",
    name: "Steve Madden Daisie Pumps",
    category: "shoes",
    image: "14.jpeg",
    price: 105,
    quantity: 1,
  },
];
